-- **************** TRIGGERS HACE DIPONIBLE DEPOSITOS DIFERIDOS AL SER PRECONCILIADOS***********************
-- ***************** JOSE RAVELO NOV-2008 *****************************************

-- ESTE TRIGGER DIFIERE LOS DEPOSITOS POR 365 DIAS O HASTA QUE SEAN PRECONCILIADOSo conciliados. PARA LLEVAR CONTROL DE DEPOSITOS Y DISPONIBILIDAD.
-- HACE DISPONIBLE LOS DEPOSITOS DIFERIDOS CUANDO ESTOS SON PRECONCILIADOS o conciliados******  
-- 
-- REPROGRAADO PARA 9024 EN OCT2016 POR:JOSERAVELO.

DROP TRIGGER [PRECONCILIACION_DEPOSITO]
GO

CREATE TRIGGER [PRECONCILIACION_DEPOSITO] ON [dbo].[SBTRAN] 
WITH ENCRYPTION
FOR UPDATE 
AS

DECLARE @NOPE INT
DECLARE @FECHA_DISPONIBLE DATETIME
DECLARE @ESTADO INT   -- 0: NORMAL 1:PRECONCILIADO 2:CONCILIADO
DECLARE @CDCD INT     -- 0:CHEQUES(-) 1:DEPOSITOS(+) 2:NC(+) 3:ND(-)
DECLARE @CODBANC VARCHAR(30)

SELECT @NOPE=NOPE, @ESTADO=ESTADO, @CDCD=CDCD, @CODBANC=CODBANC FROM INSERTED 

BEGIN

  SELECT @FECHA_DISPONIBLE=FECHA FROM SBDIFE WHERE NOPE=@NOPE
  
  

  IF @CDCD=1 
   BEGIN 
   IF @ESTADO=0  
     UPDATE SBDIFE SET CODBANC=@CODBANC, FECHALIB=@FECHA_DISPONIBLE+365 WHERE NOPE=@NOPE  
   ELSE
     UPDATE SBDIFE SET CODBANC='99999999', FECHALIB=GETDATE() WHERE NOPE=@NOPE  
   END  
  IF @CDCD=0 OR @CDCD=2 OR @CDCD=3
     DELETE SBDIFE WHERE NOPE=@NOPE  
END
