DROP TRIGGER BANDERAS
GO

CREATE TRIGGER BANDERAS ON SAFACT FOR INSERT, UPDATE
--RUTINA DE BANDERAS PARA DEPURAR ERRORES 
AS

DECLARE @DESCRIPERROR VARCHAR(200)

SELECT * FROM INSERTED 

IF ( UPDATE (NOTAS8) OR UPDATE (NOTAS9) )
BEGIN
SET @DESCRIPERROR='SE ACTUALIZO:NOTAS8 O NOTAS9 :'--+@COLOR  --+'/'+STR(@Nrounico)+'/'+@Codoper+'/'+@Codusua+'/'+@Codesta--+'/'+STR(@Fechat)
RAISERROR (@DESCRIPERROR,16,1)
ROLLBACK TRANSACTION
RETURN
END
 GO
 
 SET @DESCRIPERROR='AQUI CON:ND,NU,NP, FR, CO'+@FACTURA+' '+STR(@NROUNICO)+' '+STR(@NROREGI)+' '+CAST(@FECHARETE AS VARCHAR(40))+' '+@COMPROBANTE
     RAISERROR (@DESCRIPERROR,16,1)
     ROLLBACK TRANSACTION
     RETURN
     
     
       GO
       
 