-- PREPARA PLANTILLA BASE ORIGEN 
 --SWICHE PROTECTOR

 
 DELETE FROM SSUSRS WHERE DESCRIP NOT LIKE '%SISTEMA%'  
 DELETE FROM SACLIE WHERE CodClie NOT LIKE '990%' 
 DELETE FROM SASERV WHERE CODSERV<>'S0000' AND CODSERV <>'S9999' --NOT LIKE 'S4-%' AND CODSERV NOT LIKE 'S6-%' AND CODSERV NOT LIKE 'S8-%' AND CODSERV NOT LIKE 'S9-%' -- OJO PRESTIGE
 DELETE FROM SAVEND WHERE DESCRIP NOT LIKE '%SISTEMA%' 
 --DELETE FROM SAMECA WHERE 


 
GO
 

--