-- QUERYS PARA PREPARAR ACTUALIZACIÓN DE 8834 A 9024

-- DESACTIVA REGISTRO DE VEHUICULOS PARA QUE NO ESTORBEN EN VENTAS
UPDATE SAPROD SET Activo=0 WHERE CodInst=12

-- LOS SIGUIENTES SE REQUIEREN PARA PREPARAR DATA PARA RECIBIR MARCA DE DECLARACION MASIVA DE IVA.
-- COMPLETA EN DOCUMENTO AFECTADO CON CONTENIDO EN NOTAS9 DE VERSIONES ANTERIORES QUE NO MANEJABA DOCUMENTO AFECTADO
UPDATE SAACXP set NumeroN = Notas9 WHERE TipoCxP='81' AND Notas9 IS NOT NULL AND Notas9 <>'' AND NumeroN IS NULL

-- CORRIGE CAMPO 
UPDATE SAACXP SET Document='RET. IVA DOC.:'+NumeroN WHERE TipoCxP='81'

-- CORRIGE CAMPO
UPDATE SAACXC SET CodOper='04-002' WHERE TipoCxc='81'

--CORRIGE REGISTRO PROVENIENTE DE ANTIGUO PROCEDIMIENTO
UPDATE SAACXC SET TipoCxc='81' WHERE TipoCxc='41' AND CodOper='04-002'














