-- QUERY REPARA STOCK ALMACEN TALLER    
-- SE EJECUTA EN IMPLANTACION DE VERSION V310
-- SE DEBEN GRABAR EL RESULTADO COMO PDF X CADA BD APLICADA.
-- SE DEBE EJECUTAR POR SEGUNDA VEZ PARA VERIFICAR RESULTADO ESPERADO.
-- SOLO REPARA ALMACEN TALLER CON CANTIDAD DESPACHADA
-- NO REALIZA MAS CORRECCIONES PORQUE NO NECESARIAMENTE LAS DIFERENCIAS SE ENCUENTREN EN ALMACEN CITADO EN DESPACHO   
   
   
     DECLARE @CANTIDAD   DECIMAL (28,3)
     DECLARE @CODITEM    VARCHAR(20)
     DECLARE @ODEPOSITO  VARCHAR(10)
     DECLARE @CONTADOR   DECIMAL (28,3)
     DECLARE @CANTT      DECIMAL (28,3)
     DECLARE @CANTS      DECIMAL (28,3)
     DECLARE @CANTA      DECIMAL (28,3)
     DECLARE @DIF        VARCHAR(50)
     DECLARE @DIFT       VARCHAR(50)
     DECLARE @CONTR1     DECIMAL (28,3) -- REGISTROS REPARADOS ENTRE TALLER Y ALMACEN
     DECLARE @CONTR2     DECIMAL (28,3) -- REGISTROS CUADRADOS ENTRE TALLER Y ALMACEN
     DECLARE @CONTR3     DECIMAL (28,3) -- REGISTROS X REPARAR ENTRE ALMACENES, TALLER Y STOCK OFICIAL
     DECLARE @CONTR4     DECIMAL (28,3) -- REGISTROS CUADRADOS ENTRE ALMACENES, TALLER Y STOCK OFICIAL
     
     SET @CONTADOR = 0
     SET @CONTR1= 0
     SET @CONTR2= 0
     SET @CONTR3= 0
     SET @CONTR4= 0
     
     
     
 
      --   
 
      DECLARE MIREG SCROLL CURSOR FOR
      SELECT  DISTINCT CODITEM 
         FROM VW_C_DESPACHOS_VIVOS 
         ORDER BY CODITEM 
         
          
      OPEN MIREG
      FETCH NEXT FROM MIREG INTO @CODITEM 
      WHILE (@@FETCH_STATUS = 0) 
      BEGIN
         
         
       SELECT @ODEPOSITO=CODUBIC      FROM VW_C_DESPACHOS_VIVOS WHERE CodItem=@CODITEM  
       SELECT @CANTIDAD=SUM(CANTIDAD) FROM VW_C_DESPACHOS_VIVOS WHERE CodItem=@CODITEM 
       SELECT @CANTS=EXISTEN          FROM SAPROD               WHERE CodProd=@CODITEM 
       SELECT @CANTA=EXISTEN          FROM SAEXIS               WHERE CodProd=@CODITEM AND CodUbic=@ODEPOSITO 
       SELECT @CANTT=EXISTEN          FROM SAEXIS               WHERE CodProd=@CODITEM AND CodUbic='301'
       
       SET @CONTADOR=@CONTADOR+1         
        
       IF @CANTIDAD<>@CANTT   -- COMPARA SUMA DE TODOS LOS PEDIDOS CON CANTIDAD EXISTENTE EN TALLER
          BEGIN
           SET @DIFT='SALDOS REPARADOS ENTRE TALLER Y ALMACEN'
           SET @CONTR1=@CONTR1+1
           UPDATE SAEXIS SET Existen=@CANTIDAD WHERE CodProd=@CODITEM AND CodUbic='301'
           -- NO NECESARIAMENTE EL STOCK RESTANTE SE ENCUENTRE EN EL DEPOSITO CITADO EN EL DESPACHO
           --IF @CANTS-@CANTIDAD>=0
           --UPDATE SAEXIS SET Existen=@CANTS-@CANTIDAD WHERE CodProd=@CODITEM AND CodUbic=@ODEPOSITO
          END 
       ELSE
          BEGIN
           SET @CONTR2=@CONTR2+1
           SET @DIFT='SALDOS CUADRADOS ENTRE TALLER Y ALMACEN' 
                 
            
          END 
       
       IF @CANTT+@CANTA<>@CANTS -- COMPARA CANTIDAD EN TALLER + CANTIDAD EN ALMACEN SEA IGUAL A STOCK TOTAL DEL SISTEMA.
          BEGIN
           SET @DIF='SALDOS X REPARAR '
           SET @CONTR3=@CONTR3+1 
          END
       ELSE
          BEGIN
           SET @DIF='SALDOS CUADRADOS ENTRE ALMACENES Y STOCK OFICINAL'   
           SET @CONTR4=@CONTR4+1
          END 
          
        
       
       PRINT 'ITEM#'+STR(@CONTADOR)
       PRINT @CODITEM
       PRINT 'PEDIDOS A ALMACEN:          '+STR(@CANTIDAD) 
       PRINT 'DESPACHADOS A TALLER       :'+STR(@CANTT)+' '+@DIFT         
       PRINT '--------------------------------------------------------------------------'                 
       PRINT 'EN ALMACEN :'+@ODEPOSITO+'            :'+STR(@CANTA)
       PRINT 'TOTAL   STOCK SEGUN SISTEMA:'+STR(@CANTS) +' '+@DIF
       PRINT '--------------------------------------------------------------------------'
       PRINT 'REGISTROS REPARADOS ENTRE TALLER Y ALMACEN:'+STR(@CONTR1)
       PRINT 'REGISTROS CUADRADOS ENTRE TALLER Y ALMACEN:'+STR(@CONTR2)
       PRINT 'REGISTROS X REVISAR ENTRE ALMACENES, TALLER Y STOCK OFICIAL:'+STR(@CONTR3)
       PRINT 'REGISTROS CUADRADOS ENTRE ALMACENES, TALLER Y STOCK OFICIAL:'+STR(@CONTR4)
       
       PRINT '=========================================================================='
       
       FETCH NEXT FROM MIREG INTO @CODITEM 
      END
      CLOSE MIREG
      DEALLOCATE MIREG  
       
     