-- QUERY DE LIMPIEZA MASIVA DE TRASAS DE OR YA PROCESADAS
-- SE EJECUTA EN IMPLANTACION DE VERSION V310
-- SE DEBEN GRABAR EL RESULTADO COMO PDF X CADA BD APLICADA.
-- SE DEBE EJECUTAR POR SEGUNDA VEZ PARA VERIFICAR RESULTADO ESPERADO.
 
 DECLARE @CANTIDAD   DECIMAL (28,3)
     DECLARE @OR         VARCHAR(20)
     DECLARE @TIPOFAC    VARCHAR(10)
     DECLARE @CONTADOR   DECIMAL (28,3)
     DECLARE @CANTITF    DECIMAL (28,3)
     DECLARE @CANTITP    DECIMAL (28,3)
     DECLARE @BORRADOS   DECIMAL (28,3)
     DECLARE @NOBORRADOS  DECIMAL (28,3)
     DECLARE @DIF        VARCHAR(50)
     
       
     SET @CONTADOR = 0
     SET @BORRADOS = 0
     SET @NOBORRADOS = 0
    
      --   
 
      DECLARE MIREG SCROLL CURSOR FOR
      SELECT   DISTINCT NUMEROD 
         FROM  SAFACT  
         WHERE     (TipoFac = 'G') AND (CodOper = '01-301')
         ORDER BY NumeroD 
          
         
          
      OPEN MIREG
      FETCH NEXT FROM MIREG INTO @OR 
      WHILE (@@FETCH_STATUS = 0) 
      BEGIN
      
        SET @CONTADOR=@CONTADOR+1      
        SELECT @CANTITF = COUNT(*) FROM SAITEMFAC WHERE     (oNumero =@OR)  AND TIPOFAC='A' 
        SELECT @CANTITP = COUNT(*) FROM SAITEMFAC WHERE     (NumeroD= @OR)  AND TIPOFAC='G'

              
       IF @CANTITF<>@CANTITP
         BEGIN
          SET @DIF='NO ELIMINADO'
          SET @NOBORRADOS=@NOBORRADOS+1
         END 
       ELSE
         BEGIN
          SET @DIF='TRAZA BORRADA'   
          SET @BORRADOS=@BORRADOS+1
          DELETE FROM SAFACT WHERE NumeroD=@OR AND TipoFac='G'
          DELETE FROM SAITEMFAC WHERE NumeroD=@OR AND TipoFac='G'
         END
       
       PRINT 'ITEM#'+STR(@CONTADOR)
       PRINT 'OR#:'+@OR+' '+@DIF
       PRINT 'ITEMS FACTURADOS :'+STR(@CANTITF) 
       PRINT 'ITEMS PREFACTURA :'+STR(@CANTITP)
       PRINT 'TRAZAS BORRADAS  :'+STR(@BORRADOS)
       PRINT 'REGs NO BORRADOS  :'+STR(@NOBORRADOS) 
      
       
       FETCH NEXT FROM MIREG INTO @OR 
      END
      CLOSE MIREG
      DEALLOCATE MIREG  