
-- DETECTA INTENTO DE MODIFICACION DE REGISTROS EN SAOPER_01 Y LO CANCELA

DROP TRIGGER TG_C_NOUPDATE_SAOPER_01
GO

CREATE TRIGGER dbo.TG_C_NOUPDATE_SAOPER_01 ON SAOPER_01 FOR UPDATE
AS

BEGIN
 DECLARE @DESCRIPERROR VARCHAR(200)
 DECLARE @AHORA VARCHAR(30)

 SET @AHORA = convert(varchar(8), getdate(), 112) + 
                     ' ' + 
                     convert(varchar(12), getdate(), 114)
 SET @DESCRIPERROR='DELETE DETECTADO EN OPERACIONES A LAS:'+@AHORA  
 RAISERROR (@DESCRIPERROR,16,1)
 ROLLBACK TRANSACTION
 RETURN
END





