  
-- CONFIGURAR VALORES DEL INSERT ANTES DE EJECUTAR EL SCRIPS
-- MEJORADO PARA LA VERSION 310 DE ABRIL 2017

/****** Object:  Table [dbo].[SA_C_CONFIG]    Script Date: 04/08/2017 21:28:21 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SA_C_CONFIG]') AND type in (N'U'))
DROP TABLE [dbo].[SA_C_CONFIG]
GO
 
/****** Object:  Table [dbo].[SA_C_CONFIG]    Script Date: 04/08/2017 21:28:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SA_C_CONFIG](
	[ADAPTACION] [varchar](60) NULL,
	[ID3] [varchar](12) NULL,
	[DESCRIPCION] [varchar](60) NULL,
	[VERSION] [varchar](60) NULL,
	[NIC] [varchar](60) NULL, -- NUMERO DE IDENTIFICACION COMERCIAL (PROVINCIAS EN VENEZUELA)
	[LICMUN] [varchar](60) NULL, -- LICENCIA MUNICIPAL EN VENEZUELA.
	[ENCABEZADO] [varchar](100) NULL,
	[PIE] [varchar](100) NULL,
	[LEMA] [varchar](1000) NULL,
	[LOGO] [image] NULL,
	[LOGO2] [image] NULL
	
	
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

DECLARE @RIF VARCHAR(20)
DECLARE @RAZON VARCHAR (60)

SELECT @RIF=RIF, @RAZON=DESCRIP FROM SACONF
 

-- CONFIGURE ESTOS VALORES ANTES DE EJECUTAR EL SCRIPS

 INSERT SA_C_CONFIG (ADAPTACION, ID3, DESCRIPCION, VERSION, NIC, LICMUN, ENCABEZADO, PIE, LEMA) 
 VALUES ('CONCESIONARIO',@RIF, @RAZON, '310','','','','','')







SET ANSI_PADDING OFF
GO


