 
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[VALIDA_CODIGO_SACLIE]'))
drop TRIGGER VALIDA_CODIGO_SACLIE  
GO


if exists (select * from dbo.sysobjects where id = object_id(N'[TG_C_VALIDA_CODIGO_SACLIE]'))
drop TRIGGER TG_C_VALIDA_CODIGO_SACLIE  
GO



-- 10/04/2017 se PUSO EN MARCHA DESDE SAICLI SOLO VALIDANDO CODCLIE, EL RESTO DE LAS CONDICIONES AUN NO SE PUEDE.
-- 11/2016 ESTE TG ESTA ACTIVO PERO AUN NO FUNCIONA POR RAZONES DESCONOCIDAS 
--         SE CREE QUE LA APLICACION ACTIVO ALGUN CONDICIONANTE PARA QUE NO ATIENDA TRIGGER LA TABLA
----------------------------------------------------------------------------------------------------

if exists (select * from dbo.sysobjects where id = object_id(N'[TG_C_VALIDA_CODCLIE]'))
drop TRIGGER TG_C_VALIDA_CODCLIE  
GO
 
CREATE TRIGGER [TG_C_VALIDA_CODCLIE] ON [dbo].[SAICLI] 
WITH ENCRYPTION
FOR INSERT 
AS

 
BEGIN
DECLARE @CODCLIE VARCHAR(15)
DECLARE @ID3     VARCHAR(25)
DECLARE @DESCRIPERROR VARCHAR(200)
DECLARE @STATUSERROR INT
DECLARE @DESCRIPCION VARCHAR(40)

SELECT @CODCLIE=CODCLIE FROM INSERTED

-- Valida caracteres especiales y blanco 
IF @CODCLIE LIKE '%-%' OR @CODCLIE LIKE '%.%' OR @CODCLIE LIKE '%/%' OR @CODCLIE LIKE '% %' OR @CODCLIE LIKE '%,%'
BEGIN
  SELECT TOP 1 @DESCRIPERROR=DESCRIPCION FROM SA_CERROR WITH (NOLOCK) WHERE CODERR='01149'
  RAISERROR (@DESCRIPERROR,16,1)
 ROLLBACK TRANSACTION
 RETURN
END

-- Valida letras iniciales permitidas
IF SUBSTRING(@CODCLIE,1,1)<>'V' AND SUBSTRING(@CODCLIE,1,1)<>'E' AND SUBSTRING(@CODCLIE,1,1)<>'J' AND SUBSTRING(@CODCLIE,1,1)<>'G' AND SUBSTRING(@CODCLIE,1,1)<>'P'
BEGIN
 SELECT TOP 1 @DESCRIPERROR=DESCRIPCION FROM SA_CERROR WITH (NOLOCK) WHERE CODERR='01150'
 RAISERROR (@DESCRIPERROR,16,1)
 ROLLBACK TRANSACTION
 RETURN
END

-- Valida longitud del codigo en persona juridica
IF (SUBSTRING(@CODCLIE,1,1)='J' OR SUBSTRING(@CODCLIE,1,1)='G') AND LEN(@CODCLIE)<>10 
BEGIN
 SELECT TOP 1 @DESCRIPERROR=DESCRIPCION FROM SA_CERROR WITH (NOLOCK) WHERE CODERR='01151'
 RAISERROR (@DESCRIPERROR,16,1)
 ROLLBACK TRANSACTION
 RETURN
END



END


/* 


SELECT @CODCLIE=UPPER(CODCLIE), @ID3=UPPER(ID3),@DESCRIPCION=UPPER(DESCRIP) FROM INSERTED

IF @CODCLIE LIKE '%-%' OR @CODCLIE LIKE '%.%' OR @CODCLIE LIKE '%/%' OR @CODCLIE LIKE '% %' OR @CODCLIE LIKE '%,%'
   BEGIN
   SET @STATUSERROR=1
   SET @DESCRIPERROR='ATENCION: No debe utilizar ningun caracter especial en este campo CODIGO. INTENTE DE NUEVO'  
   END
ELSE
   IF SUBSTRING(@CODCLIE,1,1)<>'V' AND SUBSTRING(@CODCLIE,1,1)<>'E' AND SUBSTRING(@CODCLIE,1,1)<>'J' AND SUBSTRING(@CODCLIE,1,1)<>'G' AND SUBSTRING(@CODCLIE,1,1)='P'
      BEGIN
      SET @STATUSERROR=1
      SET @DESCRIPERROR='ATENCION: Utilice las letras: V - venezolana, J - juridica, E - entranjero, G - gobierno, P - PASAPORTE en el primer digito del CODIGO. Ejemplo: V99999999.'  
      END
   ELSE
      IF @ID3<>@CODCLIE AND SUBSTRING(@ID3,1,1)<>'P'
         BEGIN
         SET @STATUSERROR=1
         SET @DESCRIPERROR='ATENCION: EL CAMPO DE ID.Fiscal debe ser igual al CODIGO indicado. INTENTE DE NUEVO'  
         END
 IF @STATUSERROR=1
   BEGIN
      RAISERROR (@DESCRIPERROR,16,1)
      ROLLBACK TRANSACTION
      RETURN
   END
 ELSE
   UPDATE SACLIE SET DESCRIP=@DESCRIPCION WHERE CODCLIE=@CODCLIE
 
END
*/

 