 
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO



if exists (select * from dbo.sysobjects where id = object_id(N'[VALIDA_CODIGO_SAPROV]'))
drop TRIGGER VALIDA_CODIGO_SAPROV  
GO


-- ESTE TG ESTA ACTIVO PERO AUN NO FUNCIONA POR RAZONES DESCONOCIDAS 
-- SE CREE QUE LA APLICACION ACTIVO ALGUN CONDICIONANTE PARA QUE NO ATIENDA TRIGGER LA TABLA
----------------------------------------------------------------------------------------------------

if exists (select * from dbo.sysobjects where id = object_id(N'[TG_C_VALIDA_CODIGO_SAPROV]'))
drop TRIGGER TG_C_VALIDA_CODIGO_SAPROV 
GO

CREATE TRIGGER [TG_C_VALIDA_CODIGO_SAPROV] ON [dbo].[SAPROV] 
-- WITH ENCRYPTION
FOR INSERT 
AS

BEGIN
DECLARE @CODPROV VARCHAR(10)
DECLARE @ID3     VARCHAR(15)
DECLARE @DESCRIPERROR VARCHAR(120)
DECLARE @STATUSERROR INT
DECLARE @DESCRIPCION VARCHAR(50)
 


SELECT @CODPROV=UPPER(CODPROV), @ID3=UPPER(ID3), @DESCRIPCION=UPPER(DESCRIP) FROM INSERTED

IF @CODPROV LIKE '%-%' OR @CODPROV LIKE '%.%' OR @CODPROV LIKE '%/%'OR @CODPROV LIKE '% %' OR @CODPROV LIKE '%,%'
   BEGIN
   SET @STATUSERROR=1
   SET @DESCRIPERROR='ATENCION: No debe utilizar ningun caracter especial en el campo CODIGO. INTENTE DE NUEVO'  
   END
ELSE
   IF SUBSTRING(@CODPROV,1,1)<>'V' AND SUBSTRING(@CODPROV,1,1)<>'E' AND SUBSTRING(@CODPROV,1,1)<>'J' AND SUBSTRING(@CODPROV,1,1)<>'G'
      BEGIN
      SET @STATUSERROR=1
      SET @DESCRIPERROR='ATENCION: Utilice las letras: V - venezolana, J - juridica, E - entranjero, G - gobierno, en el primer digito del CODIGO. Ejemplo: V99999999.'    
      END
   ELSE
      IF @ID3<>@CODPROV
         BEGIN
         SET @STATUSERROR=1
         SET @DESCRIPERROR='ATENCION: EL CAMPO DE ID.Fiscal debe ser igual al CODIGO indicado. INTENTE DE NUEVO'  
         END
 IF @STATUSERROR=1
   BEGIN
      RAISERROR (@DESCRIPERROR,16,1)
      ROLLBACK TRANSACTION
      RETURN
   END
 ELSE
   UPDATE SAPROV SET DESCRIP = @DESCRIPCION WHERE CODPROV=@CODPROV
END